### ISSUE TITLE
about sourcefiles

### ISSUE THREAD

**Issue by jiangyanjavawin** [yuboona/3Dviewer#1]
hello,First thanks for your code,i have some question want to ask you.I want to change the canvas's sourcefiles through the js,here is my code:
function Onchange(){
var canvas = document.getElementById ('fullscreen');
canvas.sourcefiles = "testfiles/prim.off";
}
but the 3ds can't show on the Browser,the error is Conversion failed,Do you know how to fix it,please let me know,thank you very much.

**Comment by yuboona** [comment]
@jiangyanjavawin Hello! I don't get you about your changing canvas' sourcefiles. What are you tring to modifiy? In fact, this is a repo just wrapped the [`Online 3D Viewer`](https://github.com/kovacsv/Online3DViewer). My repo mainly focuses on using `electron` to make it a App liked thing.  

Where have you changed for your own purpose? Be more detailed, so maybe I can try to help.

**Comment by jiangyanjavawin** [comment]
您好，我觉得的您应该是中国人，咱们还是用中文交流吧。首先感谢您能在短时间内给我回信，非常感谢，我的问题可能表述的不是很清楚，我要做的是在web端显示off格式的三维模型，online 3D viewer可以，需要在canvas的sourcefiles属性中直接赋值，可以正常显示，而我需要做的是这个sourcefile属性的值是动态获取的，比如通过点击某一张图片根据图片的名称找到对应的off进行显示，我曾试图通过js方法动态给canvas的sourcefile属性赋值，就像github的问题描述中展示的，奇怪的是可以正常赋值，但是web端无法显示正常的off模型，而是显示转换失败的字样，我在github看到您也用到这个项目的一部分，所以想请教您一下，请问您有什么解决方案吗。如果有打扰到您，真的非常抱歉。祝您生活愉快。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"张大力"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月8日(星期一) 晚上11:21
收件人:&nbsp;"yuboona/3Dviewer"<3Dviewer@noreply.github.com&gt;;
抄送:&nbsp;"飞天小魔杖"<1164403787@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [yuboona/3Dviewer] about sourcefiles (#1)





 
Hello! I don't get you about your changing canvas' sourcefiles. What are you tring to modifiy? In fact, this is a repo just wrapped the Online 3D Viewer. My repo mainly focuses on using electron to make it a App liked thing.
 
Where have you changed for your own purpose? Be more detailed, so maybe I can try to help.

**Comment by yuboona** [comment]
@jiangyanjavawin 你好，我觉得你应该是想只使用这个online 3D viewer的模型渲染的部分，而文件选择的部分是希望使用自己的一套触发方式。如果是这样的一个问题，我应该是帮不上忙，这个问题主要是涉及online 3D viewer这个项目本身事件机制的问题。

我看了一下你向online 3D viewer作者的提问，我觉得你可以在向原作者描述问题的时候，更关注描述**能不能只使用其中的渲染的核心功能，强调希望使用自己的一套文件选择方法这件事**

**Comment by jiangyanjavawin** [comment]
您好，您所说的就是我要做的，我还听取您的建议，重新组织一下语言，让我的表述更加明确，感谢您的提议。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"张大力"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月9日(星期二) 上午10:15
收件人:&nbsp;"yuboona/3Dviewer"<3Dviewer@noreply.github.com&gt;;
抄送:&nbsp;"飞天小魔杖"<1164403787@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [yuboona/3Dviewer] about sourcefiles (#1)





 
@jiangyanjavawin 你好，我觉得你应该是想只使用这个online 3D viewer的模型渲染的部分，而文件选择的部分是希望使用自己的一套触发方式。如果是这样的一个问题，我应该是帮不上忙，这个问题主要是涉及online 3D viewer这个项目本身事件机制的问题。
 
我看了一下你向online 3D viewer作者的提问，我觉得你可以在向原作者描述问题的时候，更关注描述能不能只使用其中的渲染的核心功能，强调希望使用自己的一套文件选择方法这件事
